INSERT INTO Breweries (brewery_id, brewery_name) VALUES (2, 'Brouwerij Strubbe');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (3, 'Brouwerij Duvel Moortgat');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (4, 'Brouwerij Anders for GIBRIT');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (5, 'Brouwerij Strubbe for Bierfirma Den Haene');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (6, 'Brasserie St. Jean');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (7, 'Brouwerij Anders for Nonneke');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (8, 'Brouwerij du Bocq');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (9, 'De Proefbrouwerij for Brouwerij Slaapmutske');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (10, 'Microbrewery Den Triest');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (11, 'Geuzestekerij De Cam');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (12, 'Brasserie Ellezelloise');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (13, 'Brasserie de Jandrain-Jandrenouille');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (14, 'Brouwerij Belle-Vue (AB InBev)');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (15, 'Brouwerij Engilsen');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (16, 'Microbrewery Achilles');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (17, 'Brouwerij Rodenbach');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (18, 'Brasserie Dupont for Kunstencentrum Vooruit');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (19, 'Affligem Brewery (Heineken)');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (20, 'Brouwerij Liefmans');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (21, 'Brouwerij Walrave');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (22, 'De Proefbrouwerij for bierfirma Lesage');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (23, 'Brouwerij Palm for Group John Martin');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (24, 'Brouwerij Bockor');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (25, 'Brouwerij De Graal for Hopduvel Gent');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (26, 'Stadsbrouwerij Gruut');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (27, 'for bierfirma Vacas');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (28, 'De Proefbrouwerij for Het Hinkelspel');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (29, 'Brouwerij De Graal for Brouwerij De Kassei');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (30, 'Brouwerij Slagmuylder');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (31, 'Brouwerij Dilewyns');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (32, 't Hofbrouwerijke for bierfirma Montaignu');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (33, 'De Proefbrouwerij for bierfirma BVG');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (34, 'Brouwerij De Graal');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (35, 'De Proefbrouwerij for Oude Brouwerij van Zonnegem vzw');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (36, 'Scottish & Newcastle for Group John Martin');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (37, 'Brasserie la Botteresse de Sur-les-bois');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (38, 'Authentique Brasserie');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (39, 'Brouwerij Van Steenberge for Paeleman');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (40, 'Huisbrouwerij de 3 vaten');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (41, 'Brouwerij Jessenhofke by De Proefbrouwerij');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (42, 'Brasserie Saint-Monon');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (43, 'Brasserie Les 3 Fourquets commissioned by Confrérie du Tchesté de Neufchâteau');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (44, 'Brasserie de Silenrieux');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (45, 'De Proefbrouwerij for The Musketeers');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (46, 'Antwerpse Brouw Compagnie');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (47, 'Brouwerij Haacht');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (48, 'Hanssens Artisanaal');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (49, 'Brouwerij Slaghmuylder');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (50, 'Brouwerij De Graal for Bryggja');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (51, 'Brouwerij Vissenaken');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (52, 'Scheldebrouwerij');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (53, 'De proefbrouwerij for Verstraeten H&S');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (54, 'Brouwerij De Smedt commissioned by bierfirma Fisser');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (55, 'Brouwerij De Vlier for Promaco Vision');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (56, 'Brouwerij De Graal for bierfirma Vacas');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (57, 'Gueuzerie Tilquin');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (58, 'Brouwersverzet by Brouwerij Gulden Spoor');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (59, 'Brouwerij Bavik for “Mout- en Brouwhuis De Snoek”');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (60, 'De Proefbrouwerij commissioned by Brouwerij Pirlot');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (61, 'Alken-Maes (Heineken) (previously in Brouwerij De Gouden Boom)');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (62, 'De Proefbrouwerij for Microbrewery Achilles');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (63, 'Brouwerij Alvinne');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (64, 'Brouwerij Verhaeghe');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (65, 'De Proefbrouwerij for bierfirma Slaapmutske');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (66, 'Brasserie d''Ecaussinnes');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (67, 'Brouwerij Kerkom by Brouwerij Sint-Jozef');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (68, 'Scheldebrouwerij for Hobbybrouwerij Het Nest');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (69, 'Brouwerij Wilderen');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (70, 'Brasserie Du Bocq');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (71, 'De Lion à Plume by Brasserie Sainte-Hélène');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (72, 'Brouwerij Inter-Pol');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (73, 'Brouwerij Maenhout');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (74, 'Brouwerij Dubuisson');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (75, 'De Proefbrouwerij for Brouwerij The Musketeers');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (76, 'Brouwerij Strubbe for bierfirma Den Haene');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (77, 'De Proefbrouwerij for Het Waterhuis aan de bierkant');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (78, 'Brasserie Brootcoorens');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (79, 'Brouwerij ''t Gaverhopke');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (80, 'Brouwerij Anders for Brouwerij Bueckenholt');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (81, 'Brouwerij Bavik');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (82, 'De Scheldebrouwerij for Brouwerij Het Nest');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (83, 'Brasserie de Tubize');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (84, 'Brouwerij De Halve Maan');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (85, 'De Proefbrouwerij for Brouwerij De Arend (Hoboken)');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (86, 'Brouwerij Verhaeghe for Brouwerij Clarysse (bierfirma)');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (87, 'Brasserie de Silly');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (88, 'Brouwerij Strubbe for stad Lier');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (89, 'Microbrewery Achilles in De Proefbrouwerij commissioned by Paters en Prinsen');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (90, 'De Proefbrouwerij for Captain Cooker');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (91, 'Group John Martin');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (92, 'Brasserie Jean Tout Seul');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (93, 'Abbaye Notre-Dame de Saint-Rémy de Rochefort');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (94, 'Brouwerij De Graal for De Hopjutters');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (95, 'De Proefbrouwerij for De Verhuisbrouwerij');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (96, 't Hofbrouwerijke');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (97, 'Brouwerij Westmalle');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (98, 'Haacht');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (99, 'Brouwerij ''t Pakhuis');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (100, 'Brasserie des Légendes');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (101, 'Brouwerij De Graal for SLIM');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (102, 'Brouwerij Loterbol');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (103, 'Brouwerij Val-Dieu');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (104, 'Brouwerij Maenhout by Brouwerij Gulden Spoor');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (105, 'Brouwerij Smisje');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (106, 'Brouwerij Van Honsebrouck');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (107, 'Brouwerij Den Tseut');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (108, 'Brouwerij Van Steenberge for de gemeente Bierbeek en Terclavers');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (109, 'Brouwerij De Kluis (AB InBev)');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (110, 'Brouwerij De Ryck');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (111, 'Les Artisans Brasseurs');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (112, 'Brasserie Caracole');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (113, 'Brouwerij De Graal for t''Drankorgel');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (114, 'De Proefbrouwerij for Brouwerij Cluysenaer');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (115, 'Brouwerij Martens for Aldi');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (116, 'Brouwerij De Graal for De Hoevebrouwers');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (117, 'Brasserie La Botteresse de Sur-les-Bois');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (118, 'Brouwerij Bier & Karakter by Brouwerij Deca');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (119, 'Brouwerij Strubbe for “Mout- en Brouwhuis De Snoek”');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (120, 'Brasserie La Binchoise');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (121, 't Hofbrouwerijke for De Verhuisbrouwerij');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (122, 'De Scheldebrouwerij for De Lelie');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (123, 'Brouwerij De Plukker');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (124, 'Brouwerij Van Eecke for Extremis');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (125, 'Brouwerij Strubbe for den Haene');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (126, 'Brouwerij Van Den Bossche for Scouts Moen 50 jaar (2011)');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (127, 'Brouwerij Gulden Spoor');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (128, 'De Proefbrouwerij for Stepaja bvba');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (129, 'Brouwerij De Leyerth');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (130, 'Brasserie Dupont');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (131, 'Brouwerij De Ranke for Brasserie de la Senne');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (132, 'Brasserie à Vapeur');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (133, 'De Proefbrouwerij');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (134, 'Brouwerij St. Bernardus');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (135, 'De Proefbrouwerij for het Zeuntcomité');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (136, 'Brasserie du Bocq for Brouwerij Corsendonk');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (137, 'Brouwerij De Leite');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (138, 'Brasserie Saint Feuillien');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (139, 'De Proefbrouwerij for Bierfirma Trappieter');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (140, 'Brouwerij Van Steenberge for Brouwerij Paeleman');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (141, 'De Proefbrouwerij for Bierfirma Vacas');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (142, 'De Proefbrouwerij for Brouwerij De Arend');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (143, 'De Verhuisbrouwerij');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (144, 'Brasserie Artisanale de Rulles');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (145, 'Brouwerij Anders for Halen Breweries');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (146, 'Brouwerij De Graal for Brouwerij De 6 Helmen');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (147, 'Brouwerij Lefebvre');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (148, 'De Proefbrouwerij for Brouwerij Jessenhofke');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (149, 'Brouwerij Van Steenberge commissioned by Brouwerij Vanuxeem');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (150, 'Brasserie du Bocq for Broeder Jacob bvba');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (151, 'De Proefbrouwerij commissioned by De Kale Ridders');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (152, 'Brouwerij Huyghe for Oxfam world shops');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (153, 'De Proefbrouwerij for de gemeente Zwalm');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (154, 'De Struise Brouwers by Brouwerij Deca');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (155, 'Brouwerij Bosteels');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (156, 'Brouwerij De Ranke for Bierwinkel Bacelle');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (157, 'De Proefbrouwerij commissioned by De Kastelse Biervereniging');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (158, 'Brouwerij Mortal''s Beers');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (159, 'Brasserie de Bellevaux');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (160, 'Brasserie du Flo');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (161, 'Brouwerij Het Anker');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (162, 'Brouwerij Huyghe for Brouwerij Oud Beersel');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (163, 'Brouwerij Hof ten Dormaal');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (164, 'Microbrasserie de la Principauté');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (165, 'Abdij Notre-Dame d''Orval');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (166, 'Brasserie De Bouillon');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (167, 'De Proefbrouwerij for Brouwerij Pirlot');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (168, 'Achelse Kluis');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (169, 'Brouwerij Roman for Wieze Beer Belgium');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (170, 'Brasserie Cantillon');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (171, 'Zennebrouwerij');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (172, 'De Struise Brouwers');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (173, 'Brouwerij Het Alternatief by Brouwerij Alvinne');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (174, 'Brouwerij Den Toetëlèr');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (175, 'Brouwerij Girardin');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (176, 'Brasserie les 3 Fourquets');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (177, 'Brouwerij Strubbe for Biofresh Gavere');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (178, 'De Proefbrouwerij for ’t Brugs Bierinstituut');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (179, 'De Proefbrouwerij for Gageleer cbva-so');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (180, 'Brouwerij Brootcoorens');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (181, 'Brasserie de l''Abbaye du Val-Dieu for Radermacher Distillerie');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (182, 'Brasserie la Barbiot');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (183, 'Brouwerij Deca');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (184, 'Brouwerij Lupus');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (185, 'De Dolle Brouwers for Kaffee Kavijaks');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (186, 'Brasserie Saint-Feuillien');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (187, 'Brouwerij Verstraete by Brouwerij Deca');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (188, 'Brouwerij De Vlier');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (189, 'Brouwerij St. Bernardus for café Den Toerist');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (190, 'Brouwerij De Regenboog');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (191, 'Brouwerij Toye');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (192, 'Brouwerij Van den Bossche');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (193, 'Brouwerij Boelens');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (194, 'Huisbrouwerij Sint Canarus for De Verhuisbrouwerij');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (195, 'Geuzestekerij 3 Fonteinen');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (196, 'Brouwerij Anders for BOMBrewery');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (197, 'Brouwerij Het Anker (previously in Brouwerij Riva en Brouwerij Liefmans)');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (198, 'Brasserie des Géants');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (199, 'Brouwerij Danny');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (200, 'Brouwerij Kerkom');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (201, 'Brouwerij De Dochter van de Korenaar');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (202, 'Brasserie Oxymore');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (203, 'Brouwerij St-Bernardus');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (204, 'Brasserie La Binchoise (for Brasserie de Malonne)');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (205, 'Brouwerij De Landtsheer');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (206, 'Brasserie Fantôme');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (207, 'Brasserie du Bocq for Brouwerij Sterkens');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (208, 'Brouwerij Oud Beersel');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (209, 'Huisbrouwerij Sint Canarus');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (210, 'Brasserie du Bocq');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (211, 'Brouwerij De Graal for (T)Huisbrouwerij Odlo');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (212, 'Brasserie Caulier');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (213, 'De Proefbrouwerij for Buitenlust');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (214, 'Brasserie Saint-Monon for Confrérie du Busson');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (215, 'Huisbrouwerij ''t Pakhuis');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (216, 'AB InBev');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (217, 'De Proefbrouwerij for bierfirma Half Zeven');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (218, '’t Hofbrouwerijke for Montaigu');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (219, 'Brouwerij Van Eecke');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (220, 'Brouwerij De Bie');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (221, 'Sint-Sixtusabdij van Westvleteren');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (222, 'Brasserie de Bastogne');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (223, 'Brouwers Verzet in Brouwerij De Ranke');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (224, 'Brasserie de Bouillon');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (225, 'Brouwerij Van Steenberge for BIVO Drinks');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (226, 'Brasserie de l''Abbaye des Rocs');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (227, 'Brouwerij Het Alternatief by Brouwerij De Graal or Brouwerij Alvinne');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (228, 'Brasserie du Bocq for Corsendonk nv');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (229, 'Brouwerij Louwaege');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (230, 'De Proefbrouwerij for Verstraeten H&S');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (231, 't Hofbrouwerijke for Brouwerij Montaigu');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (232, 'Brouwerij Den Triest en Brouwerij Anders for Brouwerij Bueckenholt');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (233, 'Brouwerij Lindemans');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (234, 'Brasserie des Fagnes');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (235, 'Brouwerij Augrenoise');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (236, 'Brouwerij De Koninck (Duvel-Moortgat)');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (237, 'Brouwerij Boon & De Lambikstoempers');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (238, 'Brouwerij Caulier');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (239, 'Brouwerij Cnudde');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (240, 'Huisbrouwerij Sint Canarus by De Proefbrouwerij');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (241, 'Brouwerij Van Steenberge');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (242, 'Brasserie Lefebvre');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (243, 'Bierfirma NoordSter by Brouwerij De Vlier');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (244, 'Brouwerij Bios');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (245, 'Brouwerij De Graal for De Verhuisbrouwerij');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (246, 'Brouwerij Maenhout for bierfirma Proefbrouwerij d''oude maalderij');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (247, 'Brouwerij Anders for Brouwerij Henricus');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (248, 'Brouwerij Hanssens');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (249, 'Brouwerij Anders for Inglorious Brew Stars');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (250, '3 Fonteinen, Brouwerij Boon, Timmermans, Oud Beersel, Lindemans, De Troch, De Cam, Hanssens');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (251, 'Brouwerij Van Den Bossche');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (252, 'Brouwerij du Bocq for Corsendonk nv');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (253, 'Brasserie d''Achouffe (Duvel-Moortgat)');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (254, 'Brouwerij Verhaeghe Vichte commissioned by Brouwerij Vanuxeem');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (255, 'Brouwerij Lupus for (T)Huisbrouwerij Odlo');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (256, 'Brouwerij Den Herberg');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (257, 'Brouwerij Het Sas');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (258, 'Brouwerij Anders for Verenigde Brouwers');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (259, 'De Proefbrouwerij for Caulier Developpement');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (260, 'Brouwerij De Cock by Brouwerij Van Steenberge');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (261, 'Brasserie Gigi');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (262, 'Brouwerij Sint-Jozef commissioned by Zirvest Cvba');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (263, 'De Proefbrouwerij for Beerdevelopment Viven');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (264, 'Brouwerij Donum Ignis');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (265, 'Seizoensbrouwerij Vandewalle');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (266, 'Brouwerij Gulden Spoor for bierfirma Hugel');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (267, 'Brasserie La Ferme au Chêne');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (268, 'Brouwerij Den Hopperd');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (269, 'De Lion à Plume by Brasserie de Bastogne');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (270, 'Brouwerij Anders for brouwerij De Neus');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (271, 'Brouwerij Huyghe');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (272, 'Abbaye Notre-Dame de Scourmont');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (273, 'Brouwerij Nieuwhuys');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (274, 'De Proefbrouwerij for Brouwerij Troch');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (275, 'Brouwerij De Koningshoeven commissioned by Brouwerij Urthel');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (276, 'Brasserie d''Ebly');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (277, 'Brouwerij ''t Paenhuys');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (278, 'De Proefbrouwerij for Zonderik Beer Company');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (279, 'Brouwerij Palm (previously in Brouwerij De Gouden Boom)');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (280, 'De Proefbrouwerij for bierfirma Bas-bieren');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (281, 'Brouwerij Danny for Stichting Marcel De Bisschop');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (282, 'Brouwerij Het Gulden Spoor');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (283, 'Brasserie des Carrières');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (284, 'Brouwerij Martens');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (285, 'Geuzestekerij 3 fonteinen');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (286, 'Brouwerij Wieze');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (287, 'Brouwerij Angerik');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (288, 'Stadsbrouwerij Aarschot');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (289, 'Dorpsbrouwerij Humulus');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (290, 'De Proefbrouwerij for Geuzestekerij 3 Fonteinen');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (291, 'Brouwerij Roman');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (292, 'Brouwerij Strubbe for Brouwerij Crombé');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (293, 'Brouwerij en stokerij Wilderen');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (294, 'Brouwerij Van Steenberge for Microbrewery Paeleman commissioned by Kwets vzw');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (295, 'Brouwerij Opus Magnum');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (296, 'Brouwerij Sint-Jozef');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (297, 'Brouwerij Anders for Brussels Beer Project');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (298, 'Huisbrouwerij Sint Canarus for JCI Deinze en Leiestreek');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (299, 'Brouwerij Het Alternatief by Brouwerij De Graal');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (300, 'De Dolle Brouwers');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (301, 'Brouwerij Strubbe for Guldenboot nv');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (302, 'Brouwerij Palm');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (303, 'Brouwerij De Troch');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (304, 'Brouwerij Kortrijk-d’Utsel');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (305, 'Brouwerij Sint-Jozef for brouwerij Kerkom');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (306, 'Brasserie Val de Sambre');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (307, 'Brouwerij Belgoobeer by Brasserie La Binchoise');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (308, 'Brasserie La Frasnoise');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (309, 'Brasserie de Cazeau');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (310, 'Brouwerij Contreras');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (311, 'Brouwerij Martens (Bocholt)');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (312, 'Kasteelbrouwerij De Dool');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (313, 'Brouwerij De Ranke');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (314, 'Brouwerij Kerkom commissioned by drankenservice Pelgrims');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (315, 'Brouwerij Van Steenberge for De Brouwerij van Vlaanderen');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (316, 'Brouwerij Jessenhofke');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (317, 'Brouwerij Riva');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (318, 'De Scheldebrouwerij');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (319, 'Brasserie St-Feuillien');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (320, 'Brouwerij Boelens commissioned by VVV De Faluintjesstreek');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (321, 'Brouwerij De Glazen Toren');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (322, 'Brouwerij Fort Lapin');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (323, 'Brouwerij Slaghmuylder commissioned by VVV De Faluintjesstreek');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (324, 'Brouwerij Verhaeghe Vichte');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (325, 'Brouwerij De Rijck');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (326, 'Brouwerij Boelens for Bier- en Wijnhandel De Neys-Asselman');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (327, 'De Proefbrouwerij for Brouwerij Druïde');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (328, 'Brouwerij Gulden Spoor for Alain Quackelbeen');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (329, 'Brasserie Grain d''Orge');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (330, 'Huisbrouwerij Den Tseut');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (331, 'Brouwerij De Graal for Traagwater');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (332, 'Brasserie de Blaugies');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (333, 'Staminee De Garre (Brouwerij Van Steenberge)');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (334, 'Brouwerij De Graal for bierfirma Ribaldus');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (335, 'Brouwerij Sint-Jozef for Brouwerij Kerkom');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (336, 'De Proefbrouwerij for Vliegende Paard Brouwers');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (337, 'Brouwerij Van Steenberge for Hopduvel Gent');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (338, 'De Proefbrouwerij for bierfirma VALOCCO');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (339, 'Brouwerij Anders commissioned by Paters en Prinsen');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (340, 'Brasserie Millevertus');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (341, 'Brasserie de Bertinchamps');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (342, 'Brouwerij Slaapmutske');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (343, 'Brouwerij De Graal for bierfirma Johannes');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (344, 'Brasserie Sainte-Hélène');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (345, 't Hofbrouwerijke commissioned by Brouwerij Het Nest');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (346, 'Huisbrouwerij Sint-Canarus');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (347, 'Brouwerij Ter Dolen');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (348, 'Brouwerij Boon');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (349, 'Brasserie de Brunehaut');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (350, 'Brouwerij Timmermans');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (351, 'Brasserie de la Senne');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (352, 'Gageleer');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (353, 'Brouwerij Huyghe for de De Scheldebrouwerij');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (354, 'Brouwerij De Block');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (355, 'De Proefbrouwerij for de familie Neyt');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (356, 'Brouwerij DijkWaert');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (357, 'Brouwerij De Ranke for NovaBirra');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (358, 'Alken-Maes (Heineken)');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (359, 'Scheldebrouwerij for Brouwerij Het Nest');
INSERT INTO Breweries (brewery_id, brewery_name) VALUES (360, 'Brouwerij Strubbe for BioFresh');


select COUNT (*) from Breweries